root: true

env:
  node: true
  commonjs: true
  es2021: true

parserOptions:
  ecmaVersion: 12

extends:
  - eslint:recommended
  - airbnb-base

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

rules:
  no-undef: 0
  no-console: 0
  global-require: 0
  consistent-return: 0
  no-underscore-dangle: 0
  linebreak-style: 0
  indent:
    - error
    - 2
  quotes:
    - error
    - double
  semi:
    - error
    - always
  no-unused-vars: 0
