# user Routes
# create routes
POST http://localhost:4000/signup
Content-Type: application/json

{
  "username": "dffs",
  "email": "charleselloit@gmail.com",
  "password": "char-%$"
}

### signin route
POST http://localhost:4000/signin
Content-Type: application/json

{
  "email": "charleselloit@gmail.com",
  "password": "charles"
}

### create workspace
POST http://localhost:4000/workspaces/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGRhNTgyNjZkM2FlODIzYjRmZjc1ZDAiLCJpYXQiOjE2MjUyNDUwMjl9.TBlTX_HEPj7kiW7MogOADXshMwVzZgxhOBIyzgNXz4Y

{
  "title": "Digital Marketing"
}

### get all workspaces
GET http://localhost:4000/workspaces

### update workspace
POST http://localhost:4000/workspace/60d2d6487dbac32dc88a94a7
Content-Type: application/json

{
  "title": ""
}

### delete workspace
DELETE  http://localhost:4000/workspace/60d2d6487dbac32dc88a94a7

# Project Routes

# Create new Project
###
POST http://localhost:4000/projects/add
Content-Type: applicaion/json

{
  "name": "dailytasks"
}

# Search route
###
GET http://localhost:4000/search?q=digit
