# user Routes
# create routes
POST http://localhost:4000/signup
Content-Type: application/json

{
  "username": "charleselloit",
  "email": "charleselloit@gmail.com",
  "password": "charles"
}

### signin route
POST http://localhost:4000/signin
Content-Type: application/json

{
  "email": "charleselloit@gmail.com",
  "password": "charles"
}

### create workspace
POST http://localhost:4000/workspaces/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGU0MThiYjdmMTNmODQzZjRiYTkxMmYiLCJpYXQiOjE2MjU1NjEyNzl9.w_YAyPCM5F3uWfIbYFjuBVXI28Uf-qheHs0ihj-47Fw

{
  "title": "Eklow softwares"
}

### get all workspaces
GET http://localhost:4000/workspaces
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGU0MThiYjdmMTNmODQzZjRiYTkxMmYiLCJpYXQiOjE2MjU1NjEyNzl9.w_YAyPCM5F3uWfIbYFjuBVXI28Uf-qheHs0ihj-47Fw

### update workspace
POST http://localhost:4000/workspace/60d2d6487dbac32dc88a94a7
Content-Type: application/json

{
  "title": ""
}

### delete workspace
DELETE  http://localhost:4000/workspace/60d2d6487dbac32dc88a94a7

# Search route
###
GET http://localhost:4000/search?q=digit

# Project Routes

### create Project
POST http://localhost:4000/projects/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGRhNTgyNjZkM2FlODIzYjRmZjc1ZDAiLCJpYXQiOjE2MjUzODA0MTF9.bmlzvl_XewsZUd8H6oqzzFI8YwJrYjxPfm9FD1m_JiE

{
  "name": "dailytaks-api",
  "workspace": "60df597ba26732201066d89b",
  "bgColor": "lightpink"
}

### get all projects for a specific workspace
GET http://localhost:4000/projects/60df597ba26732201066d89b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGRhNTgyNjZkM2FlODIzYjRmZjc1ZDAiLCJpYXQiOjE2MjUzODA0MTF9.bmlzvl_XewsZUd8H6oqzzFI8YwJrYjxPfm9FD1m_JiE
