name: Linter 

on:
  push:
    branches: [ master, prod, staging ]
  pull_request:
    branches: [ master, staging ]

jobs:
  build:
    name: Linter # This is a name for the action.
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install --ignore-engines # this will run yarn install command to install the dependencies.
    - uses: borales/actions-yarn@v2.0.0
      with: 
        cmd: eslint:github-action # This will execute the script in the package.json.

    env:
      DEFAULT_BRANCH: staging
      OUTPUT_DETAILS: detailed
      VALIDATE_ALL_CODEBASE: false
      OUTPUT_FOLDER: Linter-Reports # dir with the reports of linting error if it happens
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}